# Generated by Django 3.2.9 on 2021-11-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255, verbose_name='ชื่อบทความ')),
                ('product_image1', models.CharField(blank=True, default='ใส่ลิงค์ภาพปกสินค้า', max_length=1000, null=True)),
                ('product_image2', models.CharField(blank=True, default='ใส่ลิงค์ภาพ1', max_length=1000, null=True)),
                ('product_image3', models.CharField(blank=True, default='ใส่ลิงค์ภาพ2', max_length=1000, null=True)),
                ('product_details', models.CharField(default='ใส่รายละเอียดสินค้า', max_length=255)),
                ('product_brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='ยี่ห้อสินค้า')),
                ('product_category', models.CharField(default='หมวดหมู่สินค้า', max_length=255)),
                ('product_categorylv2', models.CharField(default='หมวดหมู่สินค้า lv2', max_length=255)),
                ('product_categorylv3', models.CharField(default='หมวดหมู่สินค้า lv3', max_length=255)),
                ('product_view', models.IntegerField(default=0)),
                ('product_review', models.IntegerField(default=0)),
                ('product_sale', models.IntegerField(default=0)),
                ('product_price', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('shopee_link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ลิงค์สินค้าใน Shopee')),
                ('lazada_link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ลิงค์สินค้าใน Lazada')),
                ('homepro_link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ลิงค์สินค้าใน Homepro')),
                ('powerbuy_link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ลิงค์สินค้าใน Powerbuy')),
                ('JD_link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ลิงค์สินค้าใน JD')),
            ],
        ),
    ]
