# Generated by Django 3.2.9 on 2021-11-15 17:22

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255, verbose_name='ชื่อบทความ')),
                ('product_image1', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='movie')),
                ('product_image2', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='movie')),
                ('product_image3', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='movie')),
                ('product_details', models.CharField(default='ใส่รายละเอียดสินค้า', max_length=255)),
                ('product_category', models.CharField(default='หมวดหมู่สินค้า', max_length=255)),
                ('product_categorylv2', models.CharField(default='หมวดหมู่สินค้า lv2', max_length=255)),
                ('product_categorylv3', models.CharField(default='หมวดหมู่สินค้า lv3', max_length=255)),
                ('product_view', models.IntegerField(default=0)),
                ('product_review', models.IntegerField(default=0)),
                ('product_sale', models.IntegerField(default=0)),
                ('product_price', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('shopee_link', models.CharField(max_length=1000, null=True, verbose_name='ลิงค์สินค้าใน Shopee')),
                ('lazada_link', models.CharField(max_length=1000, null=True, verbose_name='ลิงค์สินค้าใน Lazada')),
                ('homepro_link', models.CharField(max_length=1000, null=True, verbose_name='ลิงค์สินค้าใน Homepro')),
                ('powerbuy_link', models.CharField(max_length=1000, null=True, verbose_name='ลิงค์สินค้าใน Shopee')),
                ('JD_link', models.CharField(max_length=1000, null=True, verbose_name='ลิงค์สินค้าใน Shopee')),
            ],
        ),
    ]
