# Generated by Django 3.2.9 on 2021-11-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_title', models.CharField(max_length=255, verbose_name='ชื่อหมวดสินค้า')),
                ('catagory_details', models.CharField(blank=True, default='รายละเอียดหมวดสินค้า', max_length=1000, null=True)),
            ],
        ),
    ]
