# Generated by Django 3.2.9 on 2021-11-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ยี่ห้อสินค้า'),
        ),
        migrations.AlterField(
            model_name='products',
            name='JD_link',
            field=models.CharField(max_length=1000, null=True, verbose_name='ลิงค์สินค้าใน JD'),
        ),
        migrations.AlterField(
            model_name='products',
            name='powerbuy_link',
            field=models.CharField(max_length=1000, null=True, verbose_name='ลิงค์สินค้าใน Powerbuy'),
        ),
    ]
